export const GET_SUBDETAIL = 'playlist/get_subdetail'
export const GET_COMMENT = 'get_commentdetail'
export const GET_MUSICURL='get_musicurl'
export const GET_SONGLIST='get_songlist'
export const GET_SONGDETAIL='get_songdetail'
export const GET_COMMENTMUSIC='get_commenetmusic'
export const GET_SIMIPLAYLIST='get_simiplaylist'
export const GET_SIMISONGS='get_simisongs'